-- Phase 1: Native Intelligence - Database Schema
-- Created: November 26, 2025
-- Purpose: Add tables and columns for auto-generated insights

-- ============================================
-- 1. Create insight_cards table
-- ============================================
create table insight_cards (
  id uuid default uuid_generate_v4() primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  type text not null, -- 'correlation', 'pattern', 'milestone', 'thematic'
  title text not null,
  content text not null,
  metadata jsonb, -- Flexible storage for type-specific data
  created_at timestamptz default now(),
  dismissed boolean default false
);

-- Row Level Security for insight_cards
alter table insight_cards enable row level security;

create policy "Users can view own insights" 
  on insight_cards for select 
  using (auth.uid() = user_id);

create policy "Users can update own insights" 
  on insight_cards for update 
  using (auth.uid() = user_id);

create policy "Users can insert own insights" 
  on insight_cards for insert 
  with check (auth.uid() = user_id);

-- ============================================
-- 2. Update reflections table
-- ============================================
alter table reflections 
add column if not exists auto_generated boolean default false;

-- ============================================
-- 3. Create indexes for performance
-- ============================================
create index if not exists idx_insight_cards_user_dismissed 
  on insight_cards(user_id, dismissed, created_at desc);

create index if not exists idx_reflections_auto_generated 
  on reflections(user_id, auto_generated, created_at desc);

-- ============================================
-- 4. Comments for documentation
-- ============================================
comment on table insight_cards is 'AI-generated insights that appear in Stream feed';
comment on column insight_cards.type is 'Type of insight: correlation, pattern, milestone, or thematic';
comment on column insight_cards.metadata is 'Flexible JSON storage for type-specific data like tags, sentiment shifts, habit IDs';
comment on column reflections.auto_generated is 'True if reflection was auto-generated by cron job, false if manually triggered';
